// frontend/src/components/Layout.tsx
import {
  ArrowLeft,
  ChevronRight,
  Heart,
  PanelLeftClose,
  PanelLeftOpen,
  Settings,
  type LucideIcon,
} from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import type { DeviceMode } from "../api/types";
import { useI18n } from "../i18n/useI18n";
import type { TranslationKey } from "../i18n/translations";
import { settingsNavItems } from "../nav/settingsNav";
import type { LiveState } from "../state/deviceContext";
import { cn } from "../ui/cn";
import { ACTIVE_ACCENT, HOVER_SURFACE, ICON_WELL } from "../ui/styles";
import { Alert } from "./Alert";
import { IconButton } from "./IconButton";
import { ShellFooter, ShellUtilityButtons } from "./ShellFooter";

const SIDEBAR_COLLAPSED_KEY = "chaya2mqtt-sidebar-collapsed";
const SETTINGS_OPEN_KEY = "chaya2mqtt-settings-nav-open";

type NavItem = {
  to: string;
  labelKey: TranslationKey;
  icon: LucideIcon;
};

const homeItem: NavItem = { to: "/", labelKey: "nav.dashboard", icon: Heart };

const settingsChildren: NavItem[] = settingsNavItems.map(({ to, labelKey, icon }) => ({
  to,
  labelKey,
  icon,
}));

const apNavItems: NavItem[] = [{ to: "/", labelKey: "nav.setup", icon: settingsNavItems[0].icon }];

const titleKeys: Record<string, TranslationKey> = {
  "/": "nav.dashboard",
  "/wifi": "nav.wifi",
  "/wifi-testing": "nav.wifi-testing",
  "/mqtt": "nav.mqtt",
  "/settings": "nav.settings",
  "/settings/device": "nav.device",
  "/update": "nav.update",
};

function isSettingsPath(pathname: string): boolean {
  return (
    pathname === "/settings" ||
    settingsChildren.some((item) => item.to === pathname) ||
    pathname === "/wifi-testing"
  );
}

function isSettingsChildPath(pathname: string): boolean {
  return settingsChildren.some((item) => item.to === pathname) || pathname === "/wifi-testing";
}

function readCollapsed(): boolean {
  try {
    return localStorage.getItem(SIDEBAR_COLLAPSED_KEY) === "1";
  } catch {
    return false;
  }
}

function readSettingsOpen(): boolean {
  try {
    return localStorage.getItem(SETTINGS_OPEN_KEY) !== "0";
  } catch {
    return true;
  }
}

function navClass(active: boolean, collapsed: boolean): string {
  return cn(
    "flex items-center rounded-xl text-sm font-semibold transition focus-ring",
    collapsed ? "justify-center px-0 py-2.5" : "gap-3 px-3 py-2.5",
    active ? ACTIVE_ACCENT : cn("text-text", HOVER_SURFACE),
  );
}

function mobileNavClass(active: boolean): string {
  return cn(
    "flex min-w-0 flex-1 flex-col items-center gap-1 rounded-lg px-1 py-2 text-[0.65rem] font-semibold transition focus-ring",
    active ? "text-accent" : "text-muted hover:text-text-bright",
  );
}

function NavItemLink({
  item,
  collapsed,
  updateAvailable,
}: {
  item: NavItem;
  collapsed: boolean;
  updateAvailable: boolean;
}) {
  const { t } = useI18n();
  const label = t(item.labelKey);
  const showDot = updateAvailable && item.to === "/update";
  return (
    <NavLink
      to={item.to}
      end={item.to === "/"}
      title={label}
      aria-label={showDot ? `${label} (${t("dashboard.update-available-title")})` : label}
      className={({ isActive }) => navClass(isActive, collapsed)}
    >
      {!collapsed ? (
        <span className="flex min-w-0 flex-1 items-center gap-2">
          <span className="truncate">{label}</span>
          {showDot ? (
            <span className="size-2 shrink-0 rounded-full bg-warning" aria-hidden />
          ) : null}
        </span>
      ) : null}
      <span className="relative inline-flex shrink-0">
        <item.icon size={18} aria-hidden />
        {showDot && collapsed ? (
          <span
            className="absolute -top-0.5 -right-0.5 size-2 rounded-full bg-warning"
            aria-hidden
          />
        ) : null}
      </span>
    </NavLink>
  );
}

export function Layout({
  children,
  mode = "sta",
  live = "live",
  updateAvailable = false,
}: {
  children: ReactNode;
  mode?: DeviceMode;
  live?: LiveState;
  updateAvailable?: boolean;
}) {
  const { pathname } = useLocation();
  const { t } = useI18n();
  const settingsActive = isSettingsPath(pathname);
  const settingsChild = isSettingsChildPath(pathname);
  const title =
    mode === "ap" && (pathname === "/" || pathname === "/wifi")
      ? t("nav.setup")
      : pathname === "/"
        ? t("app.title")
        : t(titleKeys[pathname] ?? "nav.dashboard");
  const hideChrome = pathname === "/wifi-testing";
  const [collapsed, setCollapsed] = useState(readCollapsed);
  const [settingsOpen, setSettingsOpen] = useState(() => readSettingsOpen() || settingsActive);

  useEffect(() => {
    try {
      localStorage.setItem(SIDEBAR_COLLAPSED_KEY, collapsed ? "1" : "0");
    } catch {
      /* ignore */
    }
  }, [collapsed]);

  useEffect(() => {
    try {
      localStorage.setItem(SETTINGS_OPEN_KEY, settingsOpen ? "1" : "0");
    } catch {
      /* ignore */
    }
  }, [settingsOpen]);

  useEffect(() => {
    if (settingsActive) setSettingsOpen(true);
  }, [settingsActive]);

  function toggleSettingsGroup() {
    setSettingsOpen((prev) => !prev);
  }

  return (
    <div className="min-h-screen bg-bg lg:flex lg:h-dvh lg:min-h-0 lg:overflow-hidden">
      {!hideChrome ? (
        <aside
          className={cn(
            "hidden h-full shrink-0 flex-col overflow-hidden border-r border-border bg-surface transition-[width] duration-200 ease-out lg:flex",
            collapsed ? "w-16" : "w-64",
          )}
        >
          <Link
            to="/"
            className={cn(
              "flex items-center py-4 transition hover:opacity-90 focus-ring",
              collapsed ? "justify-center px-2" : "gap-3 px-4",
            )}
            aria-label={t("nav.dashboard")}
            title={t("app.title")}
          >
            <span className={cn(ICON_WELL, "size-11 shrink-0 rounded-xl")}>
              <Heart size={18} fill="currentColor" />
            </span>
            {!collapsed ? (
              <span className="min-w-0 truncate text-xl font-bold text-text-bright">
                {t("app.title")}
              </span>
            ) : null}
          </Link>
          <nav
            className="flex min-h-0 flex-1 flex-col gap-1 overflow-y-auto p-2"
            aria-label={t("nav.main")}
          >
            {mode === "ap" ? (
              apNavItems.map((item) => (
                <NavItemLink
                  key={item.to}
                  item={item}
                  collapsed={collapsed}
                  updateAvailable={false}
                />
              ))
            ) : (
              <>
                <NavItemLink
                  item={homeItem}
                  collapsed={collapsed}
                  updateAvailable={updateAvailable}
                />
                <div className="space-y-1">
                  <div className="relative">
                    {collapsed ? (
                      <NavLink
                        to="/settings"
                        end
                        data-testid="settings-nav-link"
                        title={t("nav.settings")}
                        aria-label={t("nav.settings")}
                        className={({ isActive }) => cn(navClass(isActive, true), "w-full")}
                      >
                        <span className="relative inline-flex">
                          <Settings size={18} aria-hidden />
                          {updateAvailable ? (
                            <span
                              className="absolute -top-0.5 -right-0.5 size-2 rounded-full bg-warning"
                              aria-hidden
                            />
                          ) : null}
                        </span>
                      </NavLink>
                    ) : (
                      <>
                        <NavLink
                          to="/settings"
                          end
                          data-testid="settings-nav-link"
                          title={t("nav.settings")}
                          className={({ isActive }) =>
                            cn(navClass(isActive, false), "w-full pl-11")
                          }
                        >
                          <span className="flex min-w-0 flex-1 items-center gap-2">
                            <span className="truncate">{t("nav.settings")}</span>
                            {updateAvailable && !settingsOpen ? (
                              <span
                                className="size-2 shrink-0 rounded-full bg-warning"
                                aria-hidden
                              />
                            ) : null}
                          </span>
                          <Settings size={18} aria-hidden className="shrink-0" />
                        </NavLink>
                        <IconButton
                          type="button"
                          size="sm"
                          data-testid="settings-nav-toggle"
                          onClick={toggleSettingsGroup}
                          aria-expanded={settingsOpen}
                          aria-controls="settings-nav-group"
                          aria-label={
                            settingsOpen ? t("nav.settings-collapse") : t("nav.settings-expand")
                          }
                          className={cn(
                            "absolute top-1/2 left-1 -translate-y-1/2",
                            pathname === "/settings" ? "text-accent" : "text-muted",
                          )}
                        >
                          <ChevronRight
                            size={18}
                            aria-hidden
                            className={cn(
                              "transition-transform duration-200",
                              settingsOpen ? "rotate-90" : "",
                            )}
                          />
                        </IconButton>
                      </>
                    )}
                  </div>
                  {settingsOpen && !collapsed ? (
                    <div
                      id="settings-nav-group"
                      data-testid="settings-nav-group"
                      className="ml-3"
                      role="group"
                    >
                      {settingsChildren.map((item, index) => {
                        const isLast = index === settingsChildren.length - 1;
                        return (
                          <div key={item.to} className="relative pl-3">
                            <span
                              aria-hidden
                              className={cn(
                                "pointer-events-none absolute top-0 left-0 w-px bg-border",
                                isLast ? "h-1/2" : "bottom-0",
                              )}
                            />
                            <span
                              aria-hidden
                              className="pointer-events-none absolute top-1/2 left-0 h-px w-3 -translate-y-1/2 bg-border"
                            />
                            <NavItemLink
                              item={item}
                              collapsed={false}
                              updateAvailable={updateAvailable}
                            />
                          </div>
                        );
                      })}
                    </div>
                  ) : null}
                </div>
              </>
            )}
          </nav>
          <ShellFooter collapsed={collapsed} />
        </aside>
      ) : null}

      <div className="flex min-w-0 flex-1 flex-col lg:h-full lg:overflow-hidden">
        <header className="sticky top-0 z-30 shrink-0 border-b border-border bg-bg/95 pt-[max(0.75rem,env(safe-area-inset-top))] pb-3 backdrop-blur">
          <div className="flex w-full items-center gap-3 px-3 lg:px-4">
            {!hideChrome ? (
              <div className="hidden lg:contents">
                <IconButton
                  type="button"
                  variant="bordered"
                  data-testid="sidebar-collapse-toggle"
                  className="size-10 rounded-xl"
                  onClick={() => setCollapsed((prev) => !prev)}
                  aria-label={collapsed ? t("nav.expand") : t("nav.collapse")}
                  title={collapsed ? t("nav.expand") : t("nav.collapse")}
                  aria-expanded={!collapsed}
                >
                  {collapsed ? (
                    <PanelLeftOpen size={18} aria-hidden />
                  ) : (
                    <PanelLeftClose size={18} aria-hidden />
                  )}
                </IconButton>
              </div>
            ) : null}
            <Link
              to="/"
              data-testid="mobile-brand-home"
              className={cn(ICON_WELL, "size-10 shrink-0 rounded-xl lg:hidden")}
              aria-label={t("nav.dashboard")}
              title={t("app.title")}
            >
              <Heart size={16} fill="currentColor" aria-hidden />
            </Link>
            {settingsChild ? (
              <Link
                to="/settings"
                data-testid="settings-back"
                className={cn(
                  "inline-flex size-10 shrink-0 items-center justify-center rounded-xl border border-border bg-surface text-muted transition focus-ring lg:hidden",
                  HOVER_SURFACE,
                )}
                aria-label={t("nav.back")}
                title={t("nav.back")}
              >
                <ArrowLeft size={18} aria-hidden />
              </Link>
            ) : null}
            <h1 className="min-w-0 flex-1 truncate text-xl font-bold text-text-bright lg:text-2xl">
              {title}
            </h1>
          </div>
          <div className="mt-2 flex justify-end px-3 lg:hidden">
            <ShellUtilityButtons />
          </div>
          {live === "reconnecting" ? (
            <div className="mx-3 mt-2 lg:mx-4">
              <Alert variant="warning" className="rounded-lg px-3 py-2">
                <span className="font-medium text-warning">{t("status.live-reconnecting")}</span>
              </Alert>
            </div>
          ) : null}
        </header>

        <div className="min-h-0 flex-1 lg:overflow-y-auto">
          <main className="mx-auto w-full max-w-3xl px-4 py-4 pb-[max(4.5rem,calc(env(safe-area-inset-bottom)+3.5rem))] lg:px-6 lg:pb-8">
            {children}
          </main>
        </div>

        {!hideChrome ? (
          <nav
            className="fixed inset-x-0 bottom-0 z-30 border-t border-border bg-surface/95 px-2 pb-[max(0.35rem,env(safe-area-inset-bottom))] pt-1 backdrop-blur lg:hidden"
            aria-label={t("nav.main")}
          >
            {mode === "ap" ? (
              <div className="mx-auto flex max-w-3xl gap-1">
                {apNavItems.map((item) => (
                  <NavLink
                    key={item.to}
                    to={item.to}
                    end
                    className={({ isActive }) => mobileNavClass(isActive)}
                  >
                    <item.icon size={18} aria-hidden />
                    <span className="truncate">{t(item.labelKey)}</span>
                  </NavLink>
                ))}
              </div>
            ) : (
              <div className="mx-auto flex max-w-3xl gap-1">
                <NavLink
                  to="/"
                  end
                  title={t("nav.dashboard")}
                  aria-label={t("nav.dashboard")}
                  className={({ isActive }) => mobileNavClass(isActive)}
                >
                  <Heart size={18} aria-hidden />
                  <span className="truncate">{t("nav.dashboard")}</span>
                </NavLink>
                <NavLink
                  to="/settings"
                  end
                  title={t("nav.settings")}
                  aria-label={t("nav.settings")}
                  className={({ isActive }) => mobileNavClass(isActive || settingsActive)}
                >
                  <span className="relative inline-flex">
                    <Settings size={18} aria-hidden />
                    {updateAvailable ? (
                      <span
                        className="absolute -top-0.5 -right-0.5 size-2 rounded-full bg-warning"
                        aria-hidden
                      />
                    ) : null}
                  </span>
                  <span className="truncate">{t("nav.settings")}</span>
                </NavLink>
              </div>
            )}
          </nav>
        ) : null}
      </div>
    </div>
  );
}

// frontend/src/components/Layout.svelte
<script lang="ts">
  import {
    ArrowLeft,
    ChevronRight,
    Heart,
    PanelLeftClose,
    PanelLeftOpen,
    Settings,
  } from "@lucide/svelte";
  import type { Snippet } from "svelte";
  import type { DeviceMode } from "../api/types.ts";
  import { i18n } from "../i18n/i18n.svelte.ts";
  import type { TranslationKey } from "../i18n/translations.ts";
  import type { IconComponent } from "../nav/settingsNav.ts";
  import { settingsNavItems } from "../nav/settingsNav.ts";
  import { router } from "../nav/router.svelte.ts";
  import type { LiveState } from "../state/device.svelte.ts";
  import { cn } from "../ui/cn.ts";
  import { ACTIVE_ACCENT, HOVER_SURFACE, ICON_WELL } from "../ui/styles.ts";
  import Alert from "./Alert.svelte";
  import IconButton from "./IconButton.svelte";
  import Link from "./Link.svelte";
  import ShellFooter from "./ShellFooter.svelte";
  import ShellUtilityButtons from "./ShellUtilityButtons.svelte";

  const SIDEBAR_COLLAPSED_KEY = "chaya2mqtt-sidebar-collapsed";
  const SETTINGS_OPEN_KEY = "chaya2mqtt-settings-nav-open";

  type NavItem = {
    to: string;
    labelKey: TranslationKey;
    icon: IconComponent;
  };

  const homeItem: NavItem = { to: "/", labelKey: "nav.dashboard", icon: Heart };

  const settingsChildren: NavItem[] = settingsNavItems.map(({ to, labelKey, icon }) => ({
    to,
    labelKey,
    icon,
  }));

  const apNavItems: NavItem[] = [
    { to: "/", labelKey: "nav.setup", icon: settingsNavItems[0].icon },
  ];

  const titleKeys: Record<string, TranslationKey> = {
    "/": "nav.dashboard",
    "/wifi": "nav.wifi",
    "/wifi-testing": "nav.wifi-testing",
    "/mqtt": "nav.mqtt",
    "/settings": "nav.settings",
    "/settings/device": "nav.device",
    "/update": "nav.update",
  };

  function isSettingsPath(pathname: string): boolean {
    return (
      pathname === "/settings" ||
      settingsChildren.some((item) => item.to === pathname) ||
      pathname === "/wifi-testing"
    );
  }

  function isSettingsChildPath(pathname: string): boolean {
    return settingsChildren.some((item) => item.to === pathname) || pathname === "/wifi-testing";
  }

  function readCollapsed(): boolean {
    try {
      return localStorage.getItem(SIDEBAR_COLLAPSED_KEY) === "1";
    } catch {
      return false;
    }
  }

  function readSettingsOpen(): boolean {
    try {
      return localStorage.getItem(SETTINGS_OPEN_KEY) !== "0";
    } catch {
      return true;
    }
  }

  function navClass(active: boolean, collapsed: boolean): string {
    return cn(
      "flex items-center rounded-xl text-sm font-semibold transition focus-ring",
      collapsed ? "justify-center px-0 py-2.5" : "gap-3 px-3 py-2.5",
      active ? ACTIVE_ACCENT : cn("text-text", HOVER_SURFACE),
    );
  }

  function mobileNavClass(active: boolean): string {
    return cn(
      "flex min-w-0 flex-1 flex-col items-center gap-1 rounded-lg px-1 py-2 text-[0.65rem] font-semibold transition focus-ring",
      active ? "text-accent" : "text-muted hover:text-text-bright",
    );
  }

  function pathActive(to: string, end: boolean): boolean {
    return end
      ? router.pathname === to
      : router.pathname === to || router.pathname.startsWith(`${to}/`);
  }

  let {
    children,
    mode = "sta",
    live = "live",
    updateAvailable = false,
  }: {
    children: Snippet;
    mode?: DeviceMode;
    live?: LiveState;
    updateAvailable?: boolean;
  } = $props();

  const settingsActive = $derived(isSettingsPath(router.pathname));
  const settingsChild = $derived(isSettingsChildPath(router.pathname));
  const title = $derived(
    mode === "ap" && (router.pathname === "/" || router.pathname === "/wifi")
      ? i18n.t("nav.setup")
      : router.pathname === "/"
        ? i18n.t("app.title")
        : i18n.t(titleKeys[router.pathname] ?? "nav.dashboard"),
  );
  const hideChrome = $derived(router.pathname === "/wifi-testing");

  let collapsed = $state(readCollapsed());
  let settingsOpen = $state(readSettingsOpen() || isSettingsPath(router.pathname));

  $effect(() => {
    try {
      localStorage.setItem(SIDEBAR_COLLAPSED_KEY, collapsed ? "1" : "0");
    } catch {
      /* ignore */
    }
  });

  $effect(() => {
    try {
      localStorage.setItem(SETTINGS_OPEN_KEY, settingsOpen ? "1" : "0");
    } catch {
      /* ignore */
    }
  });

  $effect(() => {
    if (settingsActive) settingsOpen = true;
  });
</script>

<div class="min-h-screen bg-bg lg:flex lg:h-dvh lg:min-h-0 lg:overflow-hidden">
  {#if !hideChrome}
    <aside
      class={cn(
        "hidden h-full shrink-0 flex-col overflow-hidden border-r border-border bg-surface transition-[width] duration-200 ease-out lg:flex",
        collapsed ? "w-16" : "w-64",
      )}
    >
      <Link
        href="/"
        class={cn(
          "flex items-center py-4 transition hover:opacity-90 focus-ring",
          collapsed ? "justify-center px-2" : "gap-3 px-4",
        )}
        aria-label={i18n.t("nav.dashboard")}
        title={i18n.t("app.title")}
      >
        <span class={cn(ICON_WELL, "size-11 shrink-0 rounded-xl")}>
          <Heart size={18} fill="currentColor" />
        </span>
        {#if !collapsed}
          <span class="min-w-0 truncate text-xl font-bold text-text-bright">
            {i18n.t("app.title")}
          </span>
        {/if}
      </Link>
      <nav
        class="flex min-h-0 flex-1 flex-col gap-1 overflow-y-auto p-2"
        aria-label={i18n.t("nav.main")}
      >
        {#if mode === "ap"}
          {#each apNavItems as item (item.to)}
            {@render NavItemLink(item, collapsed, false)}
          {/each}
        {:else}
          {@render NavItemLink(homeItem, collapsed, updateAvailable)}
          <div class="space-y-1">
            <div class="relative">
              {#if collapsed}
                <Link
                  href="/settings"
                  end
                  data-testid="settings-nav-link"
                  title={i18n.t("nav.settings")}
                  aria-label={i18n.t("nav.settings")}
                  class={cn(navClass(pathActive("/settings", true), true), "w-full")}
                >
                  <span class="relative inline-flex">
                    <Settings size={18} aria-hidden="true" />
                    {#if updateAvailable}
                      <span
                        class="absolute -top-0.5 -right-0.5 size-2 rounded-full bg-warning"
                        aria-hidden="true"
                      ></span>
                    {/if}
                  </span>
                </Link>
              {:else}
                <Link
                  href="/settings"
                  end
                  data-testid="settings-nav-link"
                  title={i18n.t("nav.settings")}
                  class={cn(navClass(pathActive("/settings", true), false), "w-full pl-11")}
                >
                  <span class="flex min-w-0 flex-1 items-center gap-2">
                    <span class="truncate">{i18n.t("nav.settings")}</span>
                    {#if updateAvailable && !settingsOpen}
                      <span class="size-2 shrink-0 rounded-full bg-warning" aria-hidden="true"
                      ></span>
                    {/if}
                  </span>
                  <Settings size={18} aria-hidden="true" class="shrink-0" />
                </Link>
                <IconButton
                  type="button"
                  size="sm"
                  data-testid="settings-nav-toggle"
                  onclick={() => (settingsOpen = !settingsOpen)}
                  aria-expanded={settingsOpen}
                  aria-controls="settings-nav-group"
                  aria-label={settingsOpen
                    ? i18n.t("nav.settings-collapse")
                    : i18n.t("nav.settings-expand")}
                  class={cn(
                    "absolute top-1/2 left-1 -translate-y-1/2",
                    router.pathname === "/settings" ? "text-accent" : "text-muted",
                  )}
                >
                  <ChevronRight
                    size={18}
                    aria-hidden="true"
                    class={cn("transition-transform duration-200", settingsOpen ? "rotate-90" : "")}
                  />
                </IconButton>
              {/if}
            </div>
            {#if settingsOpen && !collapsed}
              <div
                id="settings-nav-group"
                data-testid="settings-nav-group"
                class="ml-3"
                role="group"
              >
                {#each settingsChildren as item, index (item.to)}
                  {@const isLast = index === settingsChildren.length - 1}
                  <div class="relative pl-3">
                    <span
                      aria-hidden="true"
                      class={cn(
                        "pointer-events-none absolute top-0 left-0 w-px bg-border",
                        isLast ? "h-1/2" : "bottom-0",
                      )}
                    ></span>
                    <span
                      aria-hidden="true"
                      class="pointer-events-none absolute top-1/2 left-0 h-px w-3 -translate-y-1/2 bg-border"
                    ></span>
                    {@render NavItemLink(item, false, updateAvailable)}
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/if}
      </nav>
      <ShellFooter {collapsed} />
    </aside>
  {/if}

  <div class="flex min-w-0 flex-1 flex-col lg:h-full lg:overflow-hidden">
    <header
      class="sticky top-0 z-30 shrink-0 border-b border-border bg-bg/95 pt-[max(0.75rem,env(safe-area-inset-top))] pb-3 backdrop-blur"
    >
      <div class="flex w-full items-center gap-3 px-3 lg:px-4">
        {#if !hideChrome}
          <div class="hidden lg:contents">
            <IconButton
              type="button"
              variant="bordered"
              data-testid="sidebar-collapse-toggle"
              class="size-10 rounded-xl"
              onclick={() => (collapsed = !collapsed)}
              aria-label={collapsed ? i18n.t("nav.expand") : i18n.t("nav.collapse")}
              title={collapsed ? i18n.t("nav.expand") : i18n.t("nav.collapse")}
              aria-expanded={!collapsed}
            >
              {#if collapsed}
                <PanelLeftOpen size={18} aria-hidden="true" />
              {:else}
                <PanelLeftClose size={18} aria-hidden="true" />
              {/if}
            </IconButton>
          </div>
        {/if}
        <Link
          href="/"
          data-testid="mobile-brand-home"
          class={cn(ICON_WELL, "size-10 shrink-0 rounded-xl lg:hidden")}
          aria-label={i18n.t("nav.dashboard")}
          title={i18n.t("app.title")}
        >
          <Heart size={16} fill="currentColor" aria-hidden="true" />
        </Link>
        {#if settingsChild}
          <Link
            href="/settings"
            data-testid="settings-back"
            class={cn(
              "inline-flex size-10 shrink-0 items-center justify-center rounded-xl border border-border bg-surface text-muted transition focus-ring lg:hidden",
              HOVER_SURFACE,
            )}
            aria-label={i18n.t("nav.back")}
            title={i18n.t("nav.back")}
          >
            <ArrowLeft size={18} aria-hidden="true" />
          </Link>
        {/if}
        <h1 class="min-w-0 flex-1 truncate text-xl font-bold text-text-bright lg:text-2xl">
          {title}
        </h1>
      </div>
      <div class="mt-2 flex justify-end px-3 lg:hidden">
        <ShellUtilityButtons />
      </div>
      {#if live === "reconnecting"}
        <div class="mx-3 mt-2 lg:mx-4">
          <Alert variant="warning" class="rounded-lg px-3 py-2">
            <span class="font-medium text-warning">{i18n.t("status.live-reconnecting")}</span>
          </Alert>
        </div>
      {/if}
    </header>

    <div class="min-h-0 flex-1 lg:overflow-y-auto">
      <main
        class="mx-auto w-full max-w-3xl px-4 py-4 pb-[max(4.5rem,calc(env(safe-area-inset-bottom)+3.5rem))] lg:px-6 lg:pb-8"
      >
        {@render children()}
      </main>
    </div>

    {#if !hideChrome}
      <nav
        class="fixed inset-x-0 bottom-0 z-30 border-t border-border bg-surface/95 px-2 pb-[max(0.35rem,env(safe-area-inset-bottom))] pt-1 backdrop-blur lg:hidden"
        aria-label={i18n.t("nav.main")}
      >
        {#if mode === "ap"}
          <div class="mx-auto flex max-w-3xl gap-1">
            {#each apNavItems as item (item.to)}
              {@const Icon = item.icon}
              <Link href={item.to} end class={mobileNavClass(pathActive(item.to, true))}>
                <Icon size={18} aria-hidden="true" />
                <span class="truncate">{i18n.t(item.labelKey)}</span>
              </Link>
            {/each}
          </div>
        {:else}
          <div class="mx-auto flex max-w-3xl gap-1">
            <Link
              href="/"
              end
              title={i18n.t("nav.dashboard")}
              aria-label={i18n.t("nav.dashboard")}
              class={mobileNavClass(pathActive("/", true))}
            >
              <Heart size={18} aria-hidden="true" />
              <span class="truncate">{i18n.t("nav.dashboard")}</span>
            </Link>
            <Link
              href="/settings"
              end
              title={i18n.t("nav.settings")}
              aria-label={i18n.t("nav.settings")}
              class={mobileNavClass(pathActive("/settings", true) || settingsActive)}
            >
              <span class="relative inline-flex">
                <Settings size={18} aria-hidden="true" />
                {#if updateAvailable}
                  <span
                    class="absolute -top-0.5 -right-0.5 size-2 rounded-full bg-warning"
                    aria-hidden="true"
                  ></span>
                {/if}
              </span>
              <span class="truncate">{i18n.t("nav.settings")}</span>
            </Link>
          </div>
        {/if}
      </nav>
    {/if}
  </div>
</div>

{#snippet NavItemLink(item: NavItem, itemCollapsed: boolean, itemUpdateAvailable: boolean)}
  {@const Icon = item.icon}
  {@const label = i18n.t(item.labelKey)}
  {@const showDot = itemUpdateAvailable && item.to === "/update"}
  {@const active = pathActive(item.to, item.to === "/")}
  <Link
    href={item.to}
    end={item.to === "/"}
    title={label}
    aria-label={showDot ? `${label} (${i18n.t("dashboard.update-available-title")})` : label}
    class={navClass(active, itemCollapsed)}
  >
    {#if !itemCollapsed}
      <span class="flex min-w-0 flex-1 items-center gap-2">
        <span class="truncate">{label}</span>
        {#if showDot}
          <span class="size-2 shrink-0 rounded-full bg-warning" aria-hidden="true"></span>
        {/if}
      </span>
    {/if}
    <span class="relative inline-flex shrink-0">
      <Icon size={18} aria-hidden="true" />
      {#if showDot && itemCollapsed}
        <span class="absolute -top-0.5 -right-0.5 size-2 rounded-full bg-warning" aria-hidden="true"
        ></span>
      {/if}
    </span>
  </Link>
{/snippet}
