// frontend/src/pages/SettingsOverviewPage.tsx
import { NavCard } from "../components/Card";
import { useI18n } from "../i18n/useI18n";
import { settingsNavItems } from "../nav/settingsNav";

export function SettingsOverviewPage() {
  const { t } = useI18n();

  return (
    <div className="grid gap-3 sm:grid-cols-2">
      {settingsNavItems.map((item) => (
        <NavCard
          key={item.to}
          to={item.to}
          title={t(item.labelKey)}
          subtitle={t(item.subtitleKey)}
          icon={item.icon}
        />
      ))}
    </div>
  );
}

// frontend/src/pages/SettingsOverviewPage.svelte
<script lang="ts">
  import NavCard from "../components/NavCard.svelte";
  import { i18n } from "../i18n/i18n.svelte.ts";
  import { settingsNavItems } from "../nav/settingsNav.ts";
</script>

<div class="grid gap-3 sm:grid-cols-2">
  {#each settingsNavItems as item (item.to)}
    <NavCard
      href={item.to}
      title={i18n.t(item.labelKey)}
      subtitle={i18n.t(item.subtitleKey)}
      icon={item.icon}
    />
  {/each}
</div>
