// frontend/src/pages/SettingsPage.tsx
import { useCallback, useEffect, useState } from "react";
import type { ShowToast } from "../components/Toast";
import { api } from "../api/client";
import type { SettingsInfo } from "../api/types";
import { ConfirmDialog } from "../components/ConfirmDialog";
import { Panel } from "../components/Card";
import { DangerButton, Field, PrimaryButton, Switch, TextInput } from "../components/Form";
import { InfoTip } from "../components/InfoTip";
import { ErrorBlock, LoadingBlock } from "../components/StateBlock";
import { useI18n } from "../i18n/useI18n";

export function SettingsPage({
  onToast,
  onDeviceRefresh,
}: {
  onToast: ShowToast;
  onDeviceRefresh: () => Promise<void>;
}) {
  const { t } = useI18n();
  const [settings, setSettings] = useState<SettingsInfo | null>(null);
  const [busy, setBusy] = useState(false);
  const [loadError, setLoadError] = useState(false);
  const [confirmReboot, setConfirmReboot] = useState(false);
  const [confirmFactory, setConfirmFactory] = useState(false);

  const load = useCallback(async () => {
    setLoadError(false);
    setSettings(null);
    try {
      setSettings(await api.getSettings());
    } catch {
      setLoadError(true);
      onToast(t("toast.settings-load-failed"), "error");
    }
  }, [onToast, t]);

  useEffect(() => {
    void load();
  }, [load]);

  async function save(e: React.FormEvent) {
    e.preventDefault();
    if (!settings) return;
    setBusy(true);
    try {
      const res = await api.saveSettings({
        reset_days: settings.resetDays,
        display_dark: settings.displayDark ? 1 : 0,
      });
      if (!res.ok) {
        onToast(t("toast.save-failed"), "error");
        return;
      }
      onToast(t("toast.saved"), "success");
      await onDeviceRefresh();
    } catch {
      onToast(t("toast.save-failed"), "error");
    } finally {
      setBusy(false);
    }
  }

  async function reboot() {
    setBusy(true);
    try {
      const res = await api.reboot();
      onToast(res.ok ? t("toast.rebooting") : t("toast.reboot-failed"), res.ok ? "info" : "error");
      setConfirmReboot(false);
    } catch {
      onToast(t("toast.reboot-failed"), "error");
    } finally {
      setBusy(false);
    }
  }

  async function factoryReset() {
    setBusy(true);
    try {
      const res = await api.factoryReset();
      onToast(
        res.ok ? t("toast.reset-factory") : t("toast.reset-factory-failed"),
        res.ok ? "info" : "error",
      );
      if (res.ok) setConfirmFactory(false);
    } catch {
      onToast(t("toast.reset-factory-failed"), "error");
    } finally {
      setBusy(false);
    }
  }

  if (loadError) {
    return (
      <ErrorBlock
        title={t("settings.load-error-title")}
        message={t("settings.load-error")}
        retryLabel={t("common.retry")}
        onRetry={() => void load()}
      />
    );
  }

  if (!settings) {
    return <LoadingBlock label={t("settings.loading")} />;
  }

  return (
    <div className="space-y-4">
      <Panel title={t("settings.general")}>
        <form className="space-y-3" onSubmit={(e) => void save(e)}>
          <Field label={t("settings.reset-days")} hint={t("settings.reset-hint")}>
            <TextInput
              type="number"
              min={0}
              max={30}
              value={settings.resetDays}
              onChange={(e) => setSettings({ ...settings, resetDays: Number(e.target.value) })}
            />
          </Field>
          <Field label={t("settings.display-dark")} hint={t("settings.display-dark-hint")}>
            <Switch
              label={t("settings.display-dark")}
              checked={settings.displayDark}
              disabled={busy}
              onChange={(displayDark) => setSettings({ ...settings, displayDark })}
            />
          </Field>
          <PrimaryButton type="submit" loading={busy}>
            {t("common.save")}
          </PrimaryButton>
        </form>
      </Panel>

      <Panel>
        <div className="space-y-3">
          <DangerButton disabled={busy} onClick={() => setConfirmReboot(true)}>
            {t("settings.reboot")}
          </DangerButton>
          <div className="flex flex-col gap-3 border-t border-border pt-3">
            <h3 className="inline-flex items-center gap-1.5 text-sm font-semibold text-text-bright">
              {t("settings.factory-reset")}
              <InfoTip text={t("settings.factory-reset-hint")} />
            </h3>
            <DangerButton disabled={busy} onClick={() => setConfirmFactory(true)}>
              {t("settings.factory-reset-confirm")}
            </DangerButton>
          </div>
        </div>
      </Panel>

      <ConfirmDialog
        open={confirmReboot}
        title={t("settings.reboot-title")}
        description={t("settings.reboot-text")}
        confirmLabel={t("settings.reboot-confirm")}
        cancelLabel={t("common.cancel")}
        confirming={busy}
        onConfirm={() => void reboot()}
        onCancel={() => setConfirmReboot(false)}
      />
      <ConfirmDialog
        open={confirmFactory}
        title={t("settings.factory-reset-title")}
        description={t("settings.factory-reset-text")}
        confirmLabel={t("settings.factory-reset-confirm")}
        cancelLabel={t("common.cancel")}
        confirming={busy}
        onConfirm={() => void factoryReset()}
        onCancel={() => setConfirmFactory(false)}
      />
    </div>
  );
}

// frontend/src/pages/SettingsPage.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import { api } from "../api/client.ts";
  import type { SettingsInfo } from "../api/types.ts";
  import ConfirmDialog from "../components/ConfirmDialog.svelte";
  import DangerButton from "../components/DangerButton.svelte";
  import ErrorBlock from "../components/ErrorBlock.svelte";
  import Field from "../components/Field.svelte";
  import InfoTip from "../components/InfoTip.svelte";
  import LoadingBlock from "../components/LoadingBlock.svelte";
  import Panel from "../components/Panel.svelte";
  import PrimaryButton from "../components/PrimaryButton.svelte";
  import Switch from "../components/Switch.svelte";
  import TextInput from "../components/TextInput.svelte";
  import type { ShowToast } from "../components/toastStack.ts";
  import { i18n } from "../i18n/i18n.svelte.ts";

  let {
    onToast,
    onDeviceRefresh,
  }: {
    onToast: ShowToast;
    onDeviceRefresh: () => Promise<void>;
  } = $props();

  let settings = $state<SettingsInfo | null>(null);
  let busy = $state(false);
  let loadError = $state(false);
  let confirmReboot = $state(false);
  let confirmFactory = $state(false);

  async function load() {
    loadError = false;
    settings = null;
    try {
      settings = await api.getSettings();
    } catch {
      loadError = true;
      onToast(i18n.t("toast.settings-load-failed"), "error");
    }
  }

  $effect(() => {
    untrack(() => {
      void load();
    });
  });

  async function save(e: SubmitEvent) {
    e.preventDefault();
    if (!settings) return;
    busy = true;
    try {
      const res = await api.saveSettings({
        reset_days: settings.resetDays,
        display_dark: settings.displayDark ? 1 : 0,
      });
      if (!res.ok) {
        onToast(i18n.t("toast.save-failed"), "error");
        return;
      }
      onToast(i18n.t("toast.saved"), "success");
      await onDeviceRefresh();
    } catch {
      onToast(i18n.t("toast.save-failed"), "error");
    } finally {
      busy = false;
    }
  }

  async function reboot() {
    busy = true;
    try {
      const res = await api.reboot();
      onToast(
        res.ok ? i18n.t("toast.rebooting") : i18n.t("toast.reboot-failed"),
        res.ok ? "info" : "error",
      );
      confirmReboot = false;
    } catch {
      onToast(i18n.t("toast.reboot-failed"), "error");
    } finally {
      busy = false;
    }
  }

  async function factoryReset() {
    busy = true;
    try {
      const res = await api.factoryReset();
      onToast(
        res.ok ? i18n.t("toast.reset-factory") : i18n.t("toast.reset-factory-failed"),
        res.ok ? "info" : "error",
      );
      if (res.ok) confirmFactory = false;
    } catch {
      onToast(i18n.t("toast.reset-factory-failed"), "error");
    } finally {
      busy = false;
    }
  }
</script>

{#if loadError}
  <ErrorBlock
    title={i18n.t("settings.load-error-title")}
    message={i18n.t("settings.load-error")}
    retryLabel={i18n.t("common.retry")}
    onRetry={() => void load()}
  />
{:else if !settings}
  <LoadingBlock label={i18n.t("settings.loading")} />
{:else}
  <div class="space-y-4">
    <Panel title={i18n.t("settings.general")}>
      <form class="space-y-3" onsubmit={(e) => void save(e)}>
        <Field label={i18n.t("settings.reset-days")} hint={i18n.t("settings.reset-hint")}>
          <TextInput type="number" min={0} max={30} bind:value={settings.resetDays} />
        </Field>
        <Field label={i18n.t("settings.display-dark")} hint={i18n.t("settings.display-dark-hint")}>
          <Switch
            label={i18n.t("settings.display-dark")}
            checked={settings.displayDark}
            disabled={busy}
            onChange={(displayDark) => {
              if (settings) settings = { ...settings, displayDark };
            }}
          />
        </Field>
        <PrimaryButton type="submit" loading={busy}>
          {i18n.t("common.save")}
        </PrimaryButton>
      </form>
    </Panel>

    <Panel>
      <div class="space-y-3">
        <DangerButton disabled={busy} onclick={() => (confirmReboot = true)}>
          {i18n.t("settings.reboot")}
        </DangerButton>
        <div class="flex flex-col gap-3 border-t border-border pt-3">
          <h3 class="inline-flex items-center gap-1.5 text-sm font-semibold text-text-bright">
            {i18n.t("settings.factory-reset")}
            <InfoTip text={i18n.t("settings.factory-reset-hint")} />
          </h3>
          <DangerButton disabled={busy} onclick={() => (confirmFactory = true)}>
            {i18n.t("settings.factory-reset-confirm")}
          </DangerButton>
        </div>
      </div>
    </Panel>

    <ConfirmDialog
      open={confirmReboot}
      title={i18n.t("settings.reboot-title")}
      description={i18n.t("settings.reboot-text")}
      confirmLabel={i18n.t("settings.reboot-confirm")}
      cancelLabel={i18n.t("common.cancel")}
      confirming={busy}
      onConfirm={() => void reboot()}
      onCancel={() => (confirmReboot = false)}
    />
    <ConfirmDialog
      open={confirmFactory}
      title={i18n.t("settings.factory-reset-title")}
      description={i18n.t("settings.factory-reset-text")}
      confirmLabel={i18n.t("settings.factory-reset-confirm")}
      cancelLabel={i18n.t("common.cancel")}
      confirming={busy}
      onConfirm={() => void factoryReset()}
      onCancel={() => (confirmFactory = false)}
    />
  </div>
{/if}
