// frontend/src/pages/WifiPage.tsx
import type { ShowToast } from "../components/Toast";
import type { DeviceInfo, WifiStatus } from "../api/types";
import { WifiSetup } from "../components/WifiSetup";

export function WifiPage({
  device,
  wifi,
  onToast,
}: {
  device: DeviceInfo;
  wifi: WifiStatus;
  onToast: ShowToast;
}) {
  return <WifiSetup device={device} wifi={wifi} onToast={onToast} showStatus />;
}

// frontend/src/pages/WifiPage.svelte
<script lang="ts">
  import type { DeviceInfo, WifiStatus } from "../api/types.ts";
  import type { ShowToast } from "../components/toastStack.ts";
  import WifiSetup from "../components/WifiSetup.svelte";

  let {
    device,
    wifi,
    onToast,
  }: {
    device: DeviceInfo;
    wifi: WifiStatus;
    onToast: ShowToast;
  } = $props();
</script>

<WifiSetup {device} {wifi} {onToast} showStatus />
